import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per top-level section, each generated from its folder (order and labels come from
// `_category_.json` files and the `sidebar_position` of each page).
const section = (dirName: string) => [{type: 'autogenerated' as const, dirName}];

const sidebars: SidebarsConfig = {
  setup: section('setup'),
  tools: section('tools'),
  projects: section('projects'),
  hardware: section('hardware'),
  games: section('games'),
  archive: section('archive'),
};

export default sidebars;
