"""Diagrams of the Setup guides (texts + layouts). Registered by make.py."""

L = lambda n: f'<i data-lucide="{n}"></i>'  # noqa: E731
LOGO = lambda s: f'<img data-logo="si:{s}">'  # noqa: E731


def tr(fr, en):
    return {"fr": fr, "en": en}


T = {
    "windows-shell": tr(
        {
            "title": "Ce qui se passe à l'ouverture d'un terminal",
            "files": "Fichiers de config", "gen": "Généré par CortX", "result": "Dans le terminal",
            "profile": ("$PROFILE", "une seule ligne"), "user": ("user_profile.ps1", "dépôt de config", "PSReadLine"),
            "cortx": ("cortx init powershell", "généré à chaque démarrage"),
            "prompt": ("Prompt", "Oh My Posh · thème", "palette"), "aliases": ("Alias et fonctions", "eza · git · yazi"),
            "zoxide": ("zoxide", "z · zi"), "integ": ("Intégration", "terminal CortX", "dossier · blocs"),
            "l_load": "charge", "l_run": "exécute",
            "legend": {"green": "Config versionnée", "blue": "Généré", "gray": "Composant"},
        },
        {
            "title": "What happens when a terminal opens",
            "files": "Config files", "gen": "Generated by CortX", "result": "In the terminal",
            "profile": ("$PROFILE", "a single line"), "user": ("user_profile.ps1", "config repo", "PSReadLine"),
            "cortx": ("cortx init powershell", "generated at every start"),
            "prompt": ("Prompt", "Oh My Posh · theme", "palette"), "aliases": ("Aliases and functions", "eza · git · yazi"),
            "zoxide": ("zoxide", "z · zi"), "integ": ("Integration", "CortX terminal", "folder · blocks"),
            "l_load": "loads", "l_run": "runs",
            "legend": {"green": "Versioned config", "blue": "Generated", "gray": "Component"},
        },
    ),
    "git-signing": tr(
        {
            "title": "Signer et pousser avec 1Password", "pc": "Poste Windows", "op": "1Password", "gh": "GitHub",
            "commit": ("git commit", "commit.gpgsign"), "push": ("git push", "core.sshCommand"),
            "sign": ("op-ssh-sign", "gpg.format = ssh"), "ssh": ("OpenSSH Windows", "pas celui de Git"),
            "agent": ("Agent SSH", "pipe nommé Windows", "autorisation"), "vault": ("Clé SSH", "jamais sur le disque"),
            "repo": ("Dépôt", "commit « vérifié »"),
            "l_sign": "signe", "l_pipe": "pipe", "l_key": "clé", "l_push": "push",
            "legend": {"green": "Secret", "blue": "Point d'entrée", "gray": "Composant"},
        },
        {
            "title": "Signing and pushing with 1Password", "pc": "Windows machine", "op": "1Password", "gh": "GitHub",
            "commit": ("git commit", "commit.gpgsign"), "push": ("git push", "core.sshCommand"),
            "sign": ("op-ssh-sign", "gpg.format = ssh"), "ssh": ("Windows OpenSSH", "not Git's own"),
            "agent": ("SSH agent", "Windows named pipe", "approval"), "vault": ("SSH key", "never on disk"),
            "repo": ("Repository", "\"verified\" commit"),
            "l_sign": "signs", "l_pipe": "pipe", "l_key": "key", "l_push": "push",
            "legend": {"green": "Secret", "blue": "Entry point", "gray": "Component"},
        },
    ),
    "tauri-updates": tr(
        {
            "title": "Les mises à jour d'une app Tauri", "ci": "GitHub", "relay": "Dépôt privé",
            "user": "Sur la machine",
            "tag": ("Tag vX.Y.Z", "git push"), "action": ("GitHub Actions", "tauri-action", "build signé"),
            "release": ("Release", "installeurs · .sig", "latest.json"),
            "proxy": ("Relais", "Vercel ou Worker", "jeton en lecture"),
            "app": ("App installée", "plugin updater", "clé publique"),
            "l_build": "construit", "l_draft": "brouillon → publiée", "l_public": "dépôt public : direct",
            "l_check": "vérifie", "l_token": "jeton",
            "legend": {"green": "Artefacts signés", "blue": "Relais", "gray": "Composant"},
            "line": "Flux", "dash": "Cas du dépôt public",
        },
        {
            "title": "Updates of a Tauri app", "ci": "GitHub", "relay": "Private repo", "user": "On the machine",
            "tag": ("Tag vX.Y.Z", "git push"), "action": ("GitHub Actions", "tauri-action", "signed build"),
            "release": ("Release", "installers · .sig", "latest.json"),
            "proxy": ("Relay", "Vercel or Worker", "read-only token"),
            "app": ("Installed app", "updater plugin", "public key"),
            "l_build": "builds", "l_draft": "draft → published", "l_public": "public repo: direct",
            "l_check": "checks", "l_token": "token",
            "legend": {"green": "Signed artifacts", "blue": "Relay", "gray": "Component"},
            "line": "Flow", "dash": "Public repo case",
        },
    ),
}


def builders(node, page):
    def windows(t):
        inner = f'''    <div class="group" id="files" style="grid-column:1;grid-row:1/5"></div>
    <div class="group main" id="gen" style="grid-column:3;grid-row:1/5"></div>
    <div class="group" id="res" style="grid-column:5/7;grid-row:1/5"></div>
    <div class="group-label" style="grid-column:1;grid-row:1">{L("file-cog")}{t["files"]}</div>
    <div class="group-label" style="grid-column:3;grid-row:1">{t["gen"]}</div>
    <div class="group-label" style="grid-column:5/7;grid-row:1">{L("square-terminal")}{t["result"]}</div>
{node("profile", "k-green fill tall", 1, 2, L("file"), t["profile"])}{node("user", "k-green fill tall", 1, 3, L("file-code"), t["user"])}{node("cortx", "k-blue fill tall", 3, "2/4", L("wand-sparkles"), t["cortx"])}{node("prompt", "tall", 5, 2, L("chevron-right"), t["prompt"])}{node("aliases", "tall", 6, 2, L("terminal"), t["aliases"])}{node("zoxide", "tall", 5, 3, L("folder-search"), t["zoxide"])}{node("integ", "tall", 6, 3, L("panels-top-left"), t["integ"])}'''
        links = [f'["profile", "user", {{ label: "{t["l_load"]}" }}]', f'["user", "cortx", {{ label: "{t["l_run"]}" }}]',
                 '["cortx", "res"]']
        return page(t, 1180, "220px 64px 220px 64px 210px 210px", "22px 96px 96px 8px", inner, links,
                    {"blocks": t["legend"]})

    def git(t):
        inner = f'''    <div class="group main" id="pc" style="grid-column:1/4;grid-row:1/4"></div>
    <div class="group" id="op" style="grid-column:5;grid-row:1/6"></div>
    <div class="group" id="gh" style="grid-column:7;grid-row:1/4"></div>
    <div class="group-label" style="grid-column:1/3;grid-row:1">{L("laptop")}{t["pc"]}</div>
    <div class="group-label" style="grid-column:5;grid-row:1">{LOGO("1password")}{t["op"]}</div>
    <div class="group-label" style="grid-column:7;grid-row:1">{LOGO("github")}{t["gh"]}</div>
{node("commit", "k-blue fill tall", 1, 2, LOGO("git"), t["commit"])}{node("sign", "tall", 3, 2, L("pen-line"), t["sign"])}{node("push", "k-blue fill tall", 1, 3, LOGO("git"), t["push"])}{node("ssh", "tall", 3, 3, L("terminal"), t["ssh"])}{node("agent", "tall", 5, "2/4", L("key-round"), t["agent"])}{node("vault", "k-green fill tall", 5, 5, L("lock"), t["vault"])}{node("repo", "tall", 7, "2/4", L("git-branch"), t["repo"])}'''
        links = [f'["commit", "sign", {{ label: "{t["l_sign"]}" }}]', '["push", "ssh"]',
                 '["sign", "agent"]', f'["ssh", "agent", {{ label: "{t["l_pipe"]}" }}]',
                 f'["agent", "vault", {{ dash: true, label: "{t["l_key"]}" }}]',
                 f'["agent", "repo", {{ label: "{t["l_push"]}" }}]']
        return page(t, 1180, "210px 64px 210px 70px 220px 70px 200px", "22px 96px 96px 34px 84px", inner, links,
                    {"blocks": t["legend"]})

    def tauri(t):
        inner = f'''    <div class="group" id="ci" style="grid-column:1/6;grid-row:1/3"></div>
    <div class="group main" id="relay" style="grid-column:5;grid-row:5/7"></div>
    <div class="group" id="user" style="grid-column:7;grid-row:1/7"></div>
    <div class="group-label" style="grid-column:1/3;grid-row:1">{LOGO("github")}{t["ci"]}</div>
    <div class="group-label" style="grid-column:5;grid-row:5">{L("shield")}{t["relay"]}</div>
    <div class="group-label" style="grid-column:7;grid-row:1">{L("monitor")}{t["user"]}</div>
{node("tag", "tall", 1, 2, L("tag"), t["tag"])}{node("action", "tall", 3, 2, L("workflow"), t["action"])}{node("release", "k-green fill tall", 5, 2, L("package"), t["release"])}{node("proxy", "k-blue fill tall", 5, 6, L("server"), t["proxy"])}{node("app", "tall", 7, 2, L("app-window"), t["app"])}'''
        links = [f'["tag", "action"]', f'["action", "release", {{ label: "{t["l_build"]}" }}]',
                 f'["release", "app", {{ dash: true, label: "{t["l_public"]}" }}]',
                 f'["proxy", "release", {{ fromAt: .9, toAt: .9, label: "{t["l_token"]}" }}]',
                 f'["app", "proxy", {{ from: "b", to: "r", label: "{t["l_check"]}" }}]']
        return page(t, 1160, "180px 56px 200px 64px 220px 110px 200px", "22px 100px 30px 30px 22px 90px", inner, links,
                    {"blocks": t["legend"], "line": t["line"], "dash": t["dash"]})

    return {"windows-shell": windows, "git-signing": git, "tauri-updates": tauri}
