// Every string shown inside the film, per language. All data is fictional.

const en = {
  lang: 'en',
  dictation: 'Idea for Zorg: let me pin a note to the top of its folder.',
  dictWords: ['Idea', 'for', 'Zorg:', 'let', 'me', 'pin', 'a', 'note', 'to', 'the', 'top', 'of', 'its', 'folder.'],
  phone: {
    title: 'Ticket idea',
    reply: 'Reply to Claude…',
    listening: 'Listening…',
    tool: 'Zorg',
    toolAction: 'create_ticket',
    toolDone: 'Created',
    answer: 'Done. I created ZORG-128 in the Zorg project, priority Medium, with the notes label.',
    model: 'Opus 5.5',
  },
  ticket: {
    ref: 'ZORG-128',
    title: 'Pin a note to the top of its folder',
    label: 'notes',
    priority: 'Medium',
    project: 'Zorg',
  },
  zorg: {
    groups: ['WORK', 'KNOWLEDGE', 'TIME', 'SYSTEM'],
    nav: ['Tickets', 'Notes', 'Reminders', 'Calendar', 'Project', 'Settings'],
    allProjects: 'Zorg',
    screen: 'Tickets',
    count: '12 tickets',
    search: 'Search… (/)',
    filter: 'Filter',
    newBtn: 'New',
    download: 'Get the desktop app',
    cards: {
      open: [
        ['Week view in the calendar', 'calendar', 1, 'JN'],
        ['Search notes by label', 'notes', 2, 'RK'],
        ['Snooze a reminder from its notification', 'reminders', 1, 'RK'],
        ['Export a note as Markdown', 'notes', 0, 'JN'],
      ],
      progress: [
        ['Shortcut for the command palette', 'ui', 2, 'RK'],
        ['Due dates on sub-tickets', 'tickets', 3, 'CL'],
      ],
      done: [
        ['Drag a ticket between projects', 'tickets', 2, 'CL'],
        ['Dark mode for the agenda', 'ui', 1, 'RK'],
        ['Attach an image to a comment', 'tickets', 1, 'CL'],
        ['Colour per project', 'ui', 0, 'JN'],
      ],
    },
    surfaces: ['Web app', 'Desktop app', 'CLI', 'MCP server'],
    surfaceSub: ['React + Supabase', 'Tauri 2', 'for my agents', 'for claude.ai'],
    detail: {
      description: 'DESCRIPTION',
      descText: 'In a folder, a pinned note stays above the others, whatever the sort order.',
      comments: 'COMMENTS & ACTIVITY',
      props: ['Status', 'Priority', 'Assignee', 'Project', 'Labels'],
      assignee: 'Claude',
      activity: 'Status → Done',
      today: 'Today',
      comment:
        'Done: notes get a Pin action, and pinned notes stay first in their folder. To check: pin a note, reload, it stays on top.',
      archive: 'Archive',
      created: 'Created today by Claude',
    },
    mobileTabs: ['Tickets', 'Notes', 'Reminders', 'Calendar', 'Project', 'Settings'],
  },
  cli: {
    showTitle: '#128 Pin a note to the top of its folder',
    meta: 'status: Open  ·  priority: 2  ·  labels: notes',
    listHead: 'ID        TITLE',
  },
  mcp: {
    call: 'tools/call  show_ticket',
    head: '# ZORG-128 — Pin a note to the top of its folder',
    rows: ['- **Project** : Zorg', '- **Status** : Open (todo)', '- **Priority** : 2 — Medium', '- **Labels** : notes'],
  },
  cortx: {
    title: 'Terminal',
    sessions: 'Sessions',
    summary: '3 · 1 agent · 1 running',
    newTerminal: 'New terminal',
    working: 'Working',
    ready: 'Ready',
    noProject: 'No project',
    prompt: 'take ticket ZORG-128',
    skill: 'Skill(zorg-tickets)',
    skillOut: 'Loaded skill: Zorg tickets',
    show: 'Bash(zorg ticket show ZORG-128)',
    showOut: 'Read 214 lines',
    status: 'Bash(zorg ticket update ZORG-128 -s status="In progress")',
    statusOut: 'ZORG-128 → In progress',
    update: 'Update(apps/web/src/screens/Notes.tsx)',
    updateOut: 'Added 12 lines, removed 2',
    service: 'Bash(cortx service start zorg web)',
    serviceOut: "Started service 'web' (PID 18432).",
    build: 'Bash(bun run build)',
    buildOut: 'built in 3.8s',
    commit: 'Bash(git commit -m "feat(notes): pin a note to the top of its folder (ZORG-128)")',
    hookOut: 'pre-commit: no secret, no e-mail address, no sensitive file',
    signedOut: '[main 7c1e9a2] feat(notes): pin a note to the top of its folder · signed',
    toastTitle: 'build · zorg',
    toastBody: 'bun run build finished in 3.8s',
    think: 'Working…',
    welcome: 'Welcome to Claude Code',
    tip: 'Try "fix the failing build"',
    serviceRow: 'web · zorg',
  },
  hook: {
    title: 'pre-commit',
    sub: 'checks what the commit contains',
    checks: ['No secret', 'No e-mail address', 'No sensitive file'],
    ok: 'Ready to sign',
    commitMsg: 'feat(notes): pin a note to the top of its folder',
    files: '3 files · +46 −3',
  },
  op: {
    app: '1Password',
    title: 'Allow git to use the SSH key “Git signing”?',
    body: 'git uses it to sign the commit.',
    key: 'Git signing',
    keyType: 'Ed25519 · SSH key',
    deny: 'Deny',
    ok: 'Authorize',
    signed: 'Signed',
    verified: 'Verified',
  },
  doc: {
    eyebrow: 'CHANGE NOTE',
    title: 'Pinned notes',
    sub: 'What changed in Zorg, why, and how to check it.',
    meta: ['Version 0.8.1', 'Ticket ZORG-128'],
    toc: 'Contents',
    sections: ['The need', 'The change', 'How to check'],
    body: [
      'In a long folder, the note I need most sinks under the newer ones.',
      'A Pin action on each note; pinned notes are sorted first.',
      'Pin a note, reload the page: it stays at the top.',
    ],
  },
  diagram: {
    title: 'From an idea to a commit',
    zones: ['PHONE', 'ZORG', 'TERMINAL · CORTX', 'GIT'],
    blocks: ['claude.ai', 'MCP server', 'Tickets', 'CLI', 'Claude Code', 'pre-commit', '1Password', 'signed commit'],
    links: ['idea', 'reads', 'checks', 'signs'],
    legend: 'Legend',
  },
  finale: 'Toolbox',
  finaleSub: 'My ecosystem',
};

const fr = {
  lang: 'fr',
  dictation: 'Idée pour Zorg : pouvoir épingler une note en haut de son dossier.',
  dictWords: ['Idée', 'pour', 'Zorg :', 'pouvoir', 'épingler', 'une', 'note', 'en', 'haut', 'de', 'son', 'dossier.'],
  phone: {
    title: 'Idée de ticket',
    reply: 'Répondre à Claude…',
    listening: 'Écoute…',
    tool: 'Zorg',
    toolAction: 'create_ticket',
    toolDone: 'Créé',
    answer: 'C’est fait : j’ai créé ZORG-128 dans le projet Zorg, priorité Moyenne, avec le label notes.',
    model: 'Opus 5.5',
  },
  ticket: {
    ref: 'ZORG-128',
    title: 'Épingler une note en haut de son dossier',
    label: 'notes',
    priority: 'Moyenne',
    project: 'Zorg',
  },
  zorg: {
    groups: ['TRAVAIL', 'CONNAISSANCE', 'TEMPS', 'SYSTÈME'],
    nav: ['Tickets', 'Notes', 'Rappels', 'Agenda', 'Projet', 'Réglages'],
    allProjects: 'Zorg',
    screen: 'Tickets',
    count: '12 tickets',
    search: 'Rechercher… (/)',
    filter: 'Filtrer',
    newBtn: 'Nouveau',
    download: 'Télécharger l’app desktop',
    cards: {
      open: [
        ['Vue semaine dans l’agenda', 'agenda', 1, 'JN'],
        ['Chercher les notes par label', 'notes', 2, 'RK'],
        ['Reporter un rappel depuis sa notification', 'rappels', 1, 'RK'],
        ['Exporter une note en Markdown', 'notes', 0, 'JN'],
      ],
      progress: [
        ['Raccourci pour la palette de commandes', 'ui', 2, 'RK'],
        ['Échéances sur les sous-tickets', 'tickets', 3, 'CL'],
      ],
      done: [
        ['Déplacer un ticket entre projets', 'tickets', 2, 'CL'],
        ['Mode sombre pour l’agenda', 'ui', 1, 'RK'],
        ['Joindre une image à un commentaire', 'tickets', 1, 'CL'],
        ['Couleur par projet', 'ui', 0, 'JN'],
      ],
    },
    surfaces: ['App web', 'App de bureau', 'CLI', 'Serveur MCP'],
    surfaceSub: ['React + Supabase', 'Tauri 2', 'pour mes agents', 'pour claude.ai'],
    detail: {
      description: 'DESCRIPTION',
      descText: 'Dans un dossier, une note épinglée reste au-dessus des autres, quel que soit le tri.',
      comments: 'COMMENTAIRES & ACTIVITÉ',
      props: ['Statut', 'Priorité', 'Assigné', 'Projet', 'Labels'],
      assignee: 'Claude',
      activity: 'Statut → Done',
      today: 'Auj.',
      comment:
        'Fait : les notes ont une action Épingler, et les notes épinglées restent en tête de leur dossier. Pour vérifier : épingler une note, recharger, elle reste en haut.',
      archive: 'Archiver',
      created: 'Créé auj. par Claude',
    },
    mobileTabs: ['Tickets', 'Notes', 'Rappels', 'Agenda', 'Projet', 'Réglages'],
  },
  cli: {
    showTitle: '#128 Épingler une note en haut de son dossier',
    meta: 'statut: Open  ·  priorité: 2  ·  labels: notes',
    listHead: 'ID        TITRE',
  },
  mcp: {
    call: 'tools/call  show_ticket',
    head: '# ZORG-128 — Épingler une note en haut de son dossier',
    rows: ['- **Projet** : Zorg', '- **Statut** : Open (todo)', '- **Priorité** : 2 — Moyenne', '- **Labels** : notes'],
  },
  cortx: {
    title: 'Terminal',
    sessions: 'Sessions',
    summary: '3 · 1 agent · 1 running',
    newTerminal: 'New terminal',
    working: 'Working',
    ready: 'Ready',
    noProject: 'No project',
    prompt: 'prends le ticket ZORG-128',
    skill: 'Skill(zorg-tickets)',
    skillOut: 'Skill chargé : Zorg tickets',
    show: 'Bash(zorg ticket show ZORG-128)',
    showOut: '214 lignes lues',
    status: 'Bash(zorg ticket update ZORG-128 -s status="In progress")',
    statusOut: 'ZORG-128 → In progress',
    update: 'Update(apps/web/src/screens/Notes.tsx)',
    updateOut: '12 lignes ajoutées, 2 supprimées',
    service: 'Bash(cortx service start zorg web)',
    serviceOut: "Started service 'web' (PID 18432).",
    build: 'Bash(bun run build)',
    buildOut: 'built in 3.8s',
    commit: 'Bash(git commit -m "feat(notes): épingler une note en haut de son dossier (ZORG-128)")',
    hookOut: 'pre-commit : aucun secret, aucune adresse e-mail, aucun fichier sensible',
    signedOut: '[main 7c1e9a2] feat(notes): épingler une note en haut de son dossier · signé',
    toastTitle: 'build · zorg',
    toastBody: 'bun run build finished in 3.8s',
    think: 'Au travail…',
    welcome: 'Bienvenue dans Claude Code',
    tip: 'Essayez « corrige le build qui échoue »',
    serviceRow: 'web · zorg',
  },
  hook: {
    title: 'pre-commit',
    sub: 'vérifie ce que contient le commit',
    checks: ['Aucun secret', 'Aucune adresse e-mail', 'Aucun fichier sensible'],
    ok: 'Prêt à signer',
    commitMsg: 'feat(notes): épingler une note en haut de son dossier',
    files: '3 fichiers · +46 −3',
  },
  op: {
    app: '1Password',
    title: 'Autoriser git à utiliser la clé SSH « Git signing » ?',
    body: 'git s’en sert pour signer le commit.',
    key: 'Git signing',
    keyType: 'Ed25519 · clé SSH',
    deny: 'Refuser',
    ok: 'Autoriser',
    signed: 'Signé',
    verified: 'Vérifié',
  },
  doc: {
    eyebrow: 'NOTE DE CHANGEMENT',
    title: 'Notes épinglées',
    sub: 'Ce qui change dans Zorg, pourquoi, et comment le vérifier.',
    meta: ['Version 0.8.1', 'Ticket ZORG-128'],
    toc: 'Sommaire',
    sections: ['Le besoin', 'Le changement', 'Comment vérifier'],
    body: [
      'Dans un long dossier, la note la plus utile disparaît sous les plus récentes.',
      'Une action Épingler sur chaque note ; les notes épinglées sont triées en premier.',
      'Épingler une note, recharger la page : elle reste en haut.',
    ],
  },
  diagram: {
    title: 'D’une idée à un commit',
    zones: ['TÉLÉPHONE', 'ZORG', 'TERMINAL · CORTX', 'GIT'],
    blocks: ['claude.ai', 'Serveur MCP', 'Tickets', 'CLI', 'Claude Code', 'pre-commit', '1Password', 'commit signé'],
    links: ['idée', 'lit', 'vérifie', 'signe'],
    legend: 'Légende',
  },
  finale: 'Toolbox',
  finaleSub: 'Mon écosystème',
};

export const COPY = { en, fr };
